### ISSUE TITLE
Текст поискового запроса отсутствует

### ISSUE THREAD

**Issue by mityukov** [alexfedoseev/sourcebuster-js#11]
Здравствуйте, не могу разобраться где брать текст, который пользователь вводил в Яндексе:
![Яндекс](https://www.evernote.com/l/ACg9wyujt7RNWYwUJkdxRB3NskApuzcmJfYB/image.png)

С гуглом то же самое:
![Гугл](https://www.evernote.com/l/ACgr7rg7eC5MzbscO9DieWnwZE7G_mOBg-QB/image.png)

В `sbjs.get.current_add.rf` текста, похоже, тоже нет. Куда копать?

**Comment by alexfedoseev** [comment]
Думаю, нигде. Поисковики давно перестали его отдавать.
