### ISSUE TITLE
Local Cookies?

### ISSUE THREAD

**Issue by theschnaz** [alexfedoseev/sourcebuster-js#22]
How can I get sourcebuster to set cookies locally?

I created a super simple page:
<!DOCTYPE html>
<html>
  <head>
    
    <script src="/sourcebuster.min.js"></script>
    
    <script>
      sbjs.init();
      console.log("created");
    </script>
  </head>
  <body >
   bust the source
    <script>
      console.log(sbjs.get.current.src);
    </script>
  </body>
</html>

In my Chrome console, I see the created log message and undefined. When I look under applications/cookies, I don't see any sb cookies.

Do I need to do something special to run soucebuster locally?

Thanks!
![screen shot 2018-08-07 at 11 09 43 am](https://user-images.githubusercontent.com/76787/43784371-fabd01cc-9a31-11e8-835b-789f9e85943c.png)
![screen shot 2018-08-07 at 11 09 35 am](https://user-images.githubusercontent.com/76787/43784372-facedc3a-9a31-11e8-94db-023d4efb0559.png)

**Comment by alexfedoseev** [comment]
I suggest to develop using valid domain name instead of `localhost`. `lvh.me` or any other you prefer ([how to setup](https://www.siteground.com/kb/how_to_use_the_hosts_file/)).
