### ISSUE TITLE
Невалидное значение typ на некоторых URL

### ISSUE THREAD

**Issue by zlebnik** [alexfedoseev/sourcebuster-js#4]
URL: http://www.sminex.com/offices?utm_term=prodazha_ofisa_&utm_source=google&utm_campaign=rw_ga_srk_ofisy_poisk_adhands&utm_medium=cpc&utm_content=86213331546&gclid=CP_e95mOwsoCFanUcgodNTAM8A
Ожидаемый typ: utm
Полученный: utm|src=google|mdm=cpc|cmp=rw_ga_srk_ofisy_poisk_adhands|cnt=86213331546|trm=prodazha_ofisa_|ses=11623380|usr=7261304|dmn=www.sminex.com

**Comment by alexfedoseev** [comment]
Привет, сорри что долго отвечаю. Прошел по ссылке, в куках вроде всё валидно, но их состав и сам скрипт модифицированы. Вряд ли я чем-то тут могу помочь.
