### ISSUE TITLE
Thanks a lot

### ISSUE THREAD

**Issue by absdata** [alexfedoseev/sourcebuster-js#5]
I can't find any special button for opinions.
But I just want to thank you for this work.
Nice, easy, and very good and detail docs.
By the way, how you do documents like this http://sbjs.rocks/sourcebuster/setup#app?
Manually or you use any tool?

**Comment by alexfedoseev** [comment]
Thanks :)

http://sbjs.rocks/sourcebuster/setup#app
This was my first React + Rails app, so it's manually.
