### ISSUE TITLE
yclid

### ISSUE THREAD

**Issue by stdex** [alexfedoseev/sourcebuster-js#6]
Яндекс ввел yclid
https://yandex.ru/support/direct-tooltips/links-for-metrica.xml

**Comment by zaharovrd** [comment]
Может подправить скрипт для определения glclid и yclid?
По гуглу описание:
[https://support.google.com/adwords/answer/3285060?hl=ru&ref_topic=3165803](url)

**Comment by alexfedoseev** [comment]
Привет. В ближайшее время к сожалению сделать ничего не смогу. PR is welcome.

**Comment by Cooluck** [comment]
Попробовал добавить поддержку yclid своей копи-пастой по-аналогии. Не разобрался только в синтаксисе версии min.js #8

**Comment by alexfedoseev** [comment]
@stdex @zaharovrd @Cooluck  Всё в мастере. Если честно, я апдейт не тестировал. Попробуйте обновиться. Если будут косяки — пишите :+1:
